# kubectl describe node <NODE_NAME> | grep Sysctls
# vm.max_map_count correspond au nombre maximal de zones mémoire virtuelle qu’un processus peut mapper.

# Elasticsearch utilise beaucoup de mappages mémoire pour ses indices et segments Lucene.

# Si cette limite est trop basse (par défaut 65530), Elasticsearch refuse de démarrer en mode production dès qu’il détecte un risque pour la stabilité.

# Avec plusieurs nœuds sur le même machine/cluster, le risque augmente, donc le bootstrap check échoue.
---
apiVersion: v1
kind: Service
metadata:
  name: es-cluster
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-cluster
spec:
  serviceName: "es-cluster"
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      securityContext:
        sysctls:
          - name: vm.max_map_count
            value: "262144"
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          env:
            - name: cluster.name
              value: "mon-cluster"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "es-cluster-0.es-cluster,es-cluster-1.es-cluster,es-cluster-2.es-cluster"
            - name: cluster.initial_master_nodes
              value: "es-cluster-0,es-cluster-1,es-cluster-2"
            - name: node.roles
              value: "master,data"
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
            - name: xpack.security.enabled
              value: "false"   # désactivé pour dev/test
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
    - metadata:
        name: es-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
