apiVersion: v1
kind: Secret
metadata:
  name: identity-secret-for-components
  namespace: default # Changez le namespace si nécessaire
type: Opaque
data:
  # Identity apps auth
  connectors-secret: c2VjcmV0X2Nvbm5lY3Rvcg== # "secret_connector" encodé en base64
  console-secret: c2VjcmV0X2NvbnNvbGU= # "secret_console" encodé en base64
  operate-secret: c2VjcmV0X29wZXJhdGU= # "secret_operate" encodé en base64
  optimize-secret: c2VjcmV0X29wdGltaXpl # "secret_optimize" encodé en base64
  tasklist-secret: c2VjcmV0X3Rhc2tsaXN0 # "secret_tasklist" encodé en base64
  zeebe-secret: c2VjcmV0X3plZWJl # "secret_zeebe" encodé en base64

  # Identity Keycloak
  admin-password: YWRtaW5fcGFzc3dvcmQ= # "admin_password" encodé en base64

  # Identity Keycloak PostgreSQL
  postgres-password: cG9zdGdyZXNfcGFzc3dvcmQ= # "postgres_password" encodé en base64
  password: ZGF0YWJhc2VfdXNlcg== # "database_user" encodé en base64

  # Web Modeler
  smtp-password: c21wdF9wYXNzd29yZA== # "smtp_password" encodé en base64
