replicaCount: 3

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 8.11.2
  pullPolicy: IfNotPresent

clusterName: es-cluster

esConfig:
  elasticsearch.yml: |
    cluster.name: ${CLUSTER_NAME}
    network.host: 0.0.0.0
    discovery.seed_hosts: es-0,es-1,es-2
    cluster.initial_master_nodes: es-0,es-1,es-2
    node.roles: [master, data, ingest]

resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"

persistence:
  enabled: true
  storageClass: "standard"
  accessMode: ReadWriteOnce
  size: 10Gi
