spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/your_db
    username: your_user
    password: your_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

zeebe:
  client:
    broker:
      gateway-address: localhost:26500
    security:
      plaintext: true

camunda:
  connector:
    polling:
      enabled: false