global:
  security:
      allowInsecureImages: true

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.9.0-debian-12-r12
  pullSecrets: []

sasl:
  client:
    users:
      - user
    passwords: password
  controller:
    user: controller_user
    password: controller_password

provisioning:
  enabled: true

listeners:
  client:
    name: BROKER

comment changer le values files présenté dans cette page internet qui définit des valeurs pour les variables d'environnement suivantes :
  - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
  - KAFKA_CFG_LISTERNER_SECURITY_PROTOCOL_MAP=CONTROLLER:SASL_PLAINTEXT,BROKER:SASL_PLAINTEXT

  - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
  - KAFKA_CFG_INTER_BROKER_LISTERNER_NAME=BROKER
  - KAFKA_CFG_ADVERTISED_LISTENERS=BROKER://:9092
  - KAFKA_CFG_LISTENERS=BROKER://:9092,CONTROLLER://:9093
  - KAFKA_CFGPROCESS_ROLES=controller,broker
  - ALLOW_PLAINTEXT_LISTENER=yes
  - KAFKA_CFG_NODE_ID=0

  Modification:
  - KAFKA_CONTROLLER_PASSWORD=controller_password
  - KAFKA_CONTROLLER_USER=controller_user
  - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
  - KAFKA_CLIENT_LISTENER_NAME=BROKER

  Default:
  - KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL=PLAIN
  - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
  - KAFKA_CFG_CONTROLLER_LISTERNER_NAMES=CONTROLLER